# Generated by Django 3.1.2 on 2021-03-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
